### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by andreykanava** [flancast90/wifi-bf#2]
![Снимок экрана от 2021-11-24 20-21-54](https://user-images.githubusercontent.com/66001105/143293836-10ac5205-27bd-4e65-9211-13b20a6db743.png)
password is not correct.

**Comment by flancast90** [comment]
Hi @andreykanava , 

Sorry that you seem to be having this issue. I'll do my best to figure out what's going on with your system, as well as recommend a few fixes right now.

On Linux systems, occasionally a bug will occur where the terminal hangs-up on the wifi connection. Already in place is a ``time.sleep`` call on Line 147, which seems to fix it on most systems, but may not work on yours. 

If you change the ``time.sleep(3)`` (Line 147) to another number (say, ``time.sleep(5)``), you may have better results.

Let me know how it goes! If this doesn't seem to work, please comment with some more info, such as your OS, its version, etc.

**Comment by PabloRuizCuevas** [comment]
I'm getting the same error, Increasing the time prevents it in some cases but, would be better to handle the situation with a couple of lines of code when trying to connect, 

The code  also needs to cover the case when the SSID is not found (that sometimes happen) and should retry the password trial and not dropped it. I made a pull request, but this part is not solved.

**Comment by flancast90** [comment]
I have code that checks the status now so that it never times out as
before. I will push as soon as I fix a few more bugs (such as spaces in the
WiFi network name causing it to crash)

**Comment by flancast90** [comment]
> 

fixed. Let me know how it works now.
