### ISSUE TITLE
Script not trying all passwords listed

### ISSUE THREAD

**Issue by PabloRuizCuevas** [flancast90/wifi-bf#4]
When the SSID is no found  (that sometimes happen, because weak connection or other reasons) the code should retry the password trial and not go to the next. In general all sort of errors no password related should cause a password retrial.

**Comment by flancast90** [comment]
good idea, I have this fixed on my end, will put here. It sounds like it's timing out maybe...

**Comment by PabloRuizCuevas** [comment]
Great! I can test it when you upload it!

**Comment by flancast90** [comment]
> Great! I can test it when you upload it!

finally found the time to fix @PabloRuizCuevas
